exclude:
  - memo.md
  - README.md

search:
  tokenizer_separator: /[\s\-/\u{3000}-\u{301C}\u{3041}-\u{3096}\u{30A1}-\u{30FA}]+/gu

# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.10.1